In [29]:
import numpy as np

a = np.array([x for x in range(10)])
b = np.sum(a ==10)
print(a.dtype)
print(b)
print(np.where(a == 10 ))

int32
0
(array([], dtype=int64),)


In [40]:
a = np.array([[1,2,3]]*3)
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]
